approve_by_comment: true
approve_regex: ^(Approved|LGTM|:\+1:)
author_approval: ignored
reject_regex: ^Rejected
reset_on_push: false
reviewers:
  members:
  - alex-glv
  - frankscholten
  - mwl
  - remmelt
  - sadovnikov
  - philwinder
  name: default
  required: 1
