approve_by_comment: true
approve_regex: ^(Approved|LGTM)
author_approval: ignored
reject_regex: ^Rejected
reset_on_push: false
reviewers:
  members:
  - alex-glv
  - frankscholten
  - mwl
  - remmelt
  - sadovnikov
  name: default
  required: 2
